### PR TITLE
Small changes and additions

### PR DESCRIPTION
**Pull request by ynezz**

### CODE REVIEW

**Comment by microbuilder** [comment]
Thanks for the pull request.  I'll be happy to commit these changes, but there are a couple issues.  First, you can already override the USB product ID by defining 'USB_PRODUCT_ID' in your config file.  There is a check in descriptors.h for this:

#ifndef USB_PRODUCT_ID
// Bitmap: MassStorage | Generic | Mouse | Key | CDC
#define PRODUCTID_BITMAP(interface, n)  ( (INTERFACES_OF_##interface ? 1 : 0) << (n) )
#define USB_PRODUCT_ID                  (0x2000 | ( PRODUCTID_BITMAP(CDC, 0) | PRODUCTID_BITMAP(HID_KEYBOARD, 1) | PRODUCTID_BITMAP(HID_MOUSE, 2) | \
                                                    PRODUCTID_BITMAP(HID_GENERIC, 3) | PRODUCTID_BITMAP(MSC, 4) ) )
#endif

I use this mechanism on some unpublished projects and would prefer to keep the mechanism this way.

The other issue is building lpcrc, and flashing the device from the makefile.  I really hesistated on whether I should include this or not.  My concern flashing devices was having something that works on both the Mac and Linux (I don't have access to a mac).  My other concern with building lpcrc is that people may not have mingw or whatever else installed and it will end up being support requests for me to explain to people how to build lpcrc, etc..  This is less of an issue on Linux where you almost certainly have a native toolchain and build tools installed, but rather unlikely on Windows.  I'm willing to include these since they are convenient, but I'll have to find a way to do some sort of platform check so that the functionality can cover Linux, Mac and Windows.

If you don't mind, I'm going to selectively commit these changes, leaving out the makefile and USB changes, but I'd be happy to discuss how the makefile can be improved in a cross-platform friendly manner.

**Comment by microbuilder** [comment]
I just pushed an update that takes into account all the changes except the lpcrc and flashing stuff.  I'll be happy to add these in as well, but I'll need a cross-platform solution for it (specifically 'flash' since building lpcrc is straight forward if you have a native GCC toolchain + build tools installed).  I'd also like to add lpc2isp as an option from the makefile, but need to test this out on the three main platforms.

**Comment by ynezz** [comment]
Kevin Townsend notifications@github.com [2013-04-13 04:01:22]:

> #ifndef USB_PRODUCT_ID
> ...
> I use this mechanism on some unpublished projects and would prefer to keep the mechanism this way.

Ok. It's just not that consistent as it would be with CFG_ prefix :)

> The other issue is building lpcrc, and flashing the device from the
> makefile.  I really hesistated on whether I should include this or not.  My
> concern flashing devices was having something that works on both the Mac and
> Linux (I don't have access to a mac).  My other concern with building lpcrc
> is that people may not have mingw or whatever else installed and it will end
> up being support requests for me to explain to people how to build lpcrc,
> etc..

Ok, the thing is, that on Windows and maybe on OSX (I don't have Mac either)
simply copying the binary over to the mass storage device is enough. On Linux
it's not the case and I've spent few ours figuring this out...

> This is less of an issue on Linux where you almost certainly have a
> native toolchain and build tools installed, but rather unlikely on Windows.
> I'm willing to include these since they are convenient, but I'll have to
> find a way to do some sort of platform check so that the functionality can
> cover Linux, Mac and Windows.

Ok.

> If you don't mind, I'm going to selectively commit these changes, leaving
> out the makefile and USB changes, but I'd be happy to discuss how the
> makefile can be improved in a cross-platform friendly manner.

No problem at all.

**Comment by ynezz** [comment]
Kevin Townsend notifications@github.com [2013-04-13 04:24:56]:

> I'd also like to add lpc2isp as an option from the makefile, but need to
> test this out on the three main platforms.

What's the use case for lpc2isp? Support flashing of MCUs without the USB
ROM drivers?

**Comment by microbuilder** [comment]
Let me fire up a Linux box and I'll test out the flash addition to the makefile.   I can commit that since it's not mandatory, and you're right that it's pretty painless to just drag and drop if you're using Windows and Mac.

**Comment by microbuilder** [comment]
I just committed and pushed a change to the makefile for 'make flash'.  Thanks again for the contribution.

**Pull request closed without merging**
